[package]
name = "game-template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
clap = { version = "4.4.11", features = ["derive"] }

[features]
default = ["debug"]
debug = ["bevy/dynamic_linking"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
